#     ifndef VERSION_F90
#     define VERSION_F90

#     include "../system/text_format.F90"


      module version


            use::text_formatting


            implicit none


            character(15),parameter,private::this="v2.0"
            character(15),          private::that

            public:: read_version
            public::write_version


      contains


            subroutine  read_version()


                  implicit none


                  integer::unit
                  integer::stat


                   open(newunit=unit,file="ifort/bin/version",status="old",iostat=stat)
                   read(        unit,                                "(a)"            ) that
                  close(        unit                                                  )

                  if(that/=this) stop t_red//"Error: cannot load files generated by incompatible version of the program"//t_normal
                  if(stat/=0000) stop t_yellow//"Warning: when running the program for the first time, no"//t_bold//"-c"//t_normal


        end subroutine  read_version!


            subroutine write_version()


                  implicit none


                  integer::unit


                   open(newunit=unit,file="ifort/bin/version"             )
                  write(        unit,                                "(a)") this
                  close(        unit                                      )


        end subroutine write_version!


  end module version


#  endif
